#生产环境配置 原生jar包启动时 采用 --spring.profiles.active = prod
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://47.113.185.5:3306/user_center
    password: rootlnc
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
      host: 47.113.185.5
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 100ms
          min-idle: 0
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
#        same-site: None
#        secure: true  #是否仅仅在https的链接下，才提交cookie
#        http-only: true  #是否允许js读取cookie
        domain: lncanswer.cn #开发环境下设置domain为服务器域名
